# Generated by Django 5.1.2 on 2024-10-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField()),
                ('birthplace', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
            ],
        ),
    ]
